#!/bin/bash
#BSUB -J step9c_get_significant_QTLs
#BSUB -o step9c_get_significant_QTLs.out
#BSUB -e step9c_get_significant_QTLs.err

bsub < QTL_getters/get_QTLs_chr1_P0.sh
bsub < QTL_getters/get_QTLs_chr1_P1.sh
bsub < QTL_getters/get_QTLs_chr1_P2.sh
bsub < QTL_getters/get_QTLs_chr1_P3.sh
bsub < QTL_getters/get_QTLs_chr1_P4.sh
bsub < QTL_getters/get_QTLs_chr1_P5.sh
bsub < QTL_getters/get_QTLs_chr1_P6.sh
bsub < QTL_getters/get_QTLs_chr1_P7.sh
bsub < QTL_getters/get_QTLs_chr1_P8.sh
bsub < QTL_getters/get_QTLs_chr1_P9.sh
bsub < QTL_getters/get_QTLs_chr1_P10.sh
bsub < QTL_getters/get_QTLs_chr1_P11.sh
bsub < QTL_getters/get_QTLs_chr1_P12.sh
bsub < QTL_getters/get_QTLs_chr1_P13.sh
bsub < QTL_getters/get_QTLs_chr1_P14.sh
bsub < QTL_getters/get_QTLs_chr1_P15.sh

bsub < QTL_getters/get_QTLs_chr2_P0.sh
bsub < QTL_getters/get_QTLs_chr2_P1.sh
bsub < QTL_getters/get_QTLs_chr2_P2.sh
bsub < QTL_getters/get_QTLs_chr2_P3.sh
bsub < QTL_getters/get_QTLs_chr2_P4.sh
bsub < QTL_getters/get_QTLs_chr2_P5.sh
bsub < QTL_getters/get_QTLs_chr2_P6.sh
bsub < QTL_getters/get_QTLs_chr2_P7.sh
bsub < QTL_getters/get_QTLs_chr2_P8.sh
bsub < QTL_getters/get_QTLs_chr2_P9.sh
bsub < QTL_getters/get_QTLs_chr2_P10.sh
bsub < QTL_getters/get_QTLs_chr2_P11.sh
bsub < QTL_getters/get_QTLs_chr2_P12.sh
bsub < QTL_getters/get_QTLs_chr2_P13.sh
bsub < QTL_getters/get_QTLs_chr2_P14.sh
bsub < QTL_getters/get_QTLs_chr2_P15.sh

bsub < QTL_getters/get_QTLs_chr3_P0.sh
bsub < QTL_getters/get_QTLs_chr3_P1.sh
bsub < QTL_getters/get_QTLs_chr3_P2.sh
bsub < QTL_getters/get_QTLs_chr3_P3.sh
bsub < QTL_getters/get_QTLs_chr3_P4.sh
bsub < QTL_getters/get_QTLs_chr3_P5.sh
bsub < QTL_getters/get_QTLs_chr3_P6.sh
bsub < QTL_getters/get_QTLs_chr3_P7.sh
bsub < QTL_getters/get_QTLs_chr3_P8.sh
bsub < QTL_getters/get_QTLs_chr3_P9.sh
bsub < QTL_getters/get_QTLs_chr3_P10.sh
bsub < QTL_getters/get_QTLs_chr3_P11.sh
bsub < QTL_getters/get_QTLs_chr3_P12.sh
bsub < QTL_getters/get_QTLs_chr3_P13.sh
bsub < QTL_getters/get_QTLs_chr3_P14.sh
bsub < QTL_getters/get_QTLs_chr3_P15.sh

bsub < QTL_getters/get_QTLs_chr4_P0.sh
bsub < QTL_getters/get_QTLs_chr4_P1.sh
bsub < QTL_getters/get_QTLs_chr4_P2.sh
bsub < QTL_getters/get_QTLs_chr4_P3.sh
bsub < QTL_getters/get_QTLs_chr4_P4.sh
bsub < QTL_getters/get_QTLs_chr4_P5.sh
bsub < QTL_getters/get_QTLs_chr4_P6.sh
bsub < QTL_getters/get_QTLs_chr4_P7.sh
bsub < QTL_getters/get_QTLs_chr4_P8.sh
bsub < QTL_getters/get_QTLs_chr4_P9.sh
bsub < QTL_getters/get_QTLs_chr4_P10.sh
bsub < QTL_getters/get_QTLs_chr4_P11.sh
bsub < QTL_getters/get_QTLs_chr4_P12.sh
bsub < QTL_getters/get_QTLs_chr4_P13.sh
bsub < QTL_getters/get_QTLs_chr4_P14.sh
bsub < QTL_getters/get_QTLs_chr4_P15.sh

bsub < QTL_getters/get_QTLs_chr5_P0.sh
bsub < QTL_getters/get_QTLs_chr5_P1.sh
bsub < QTL_getters/get_QTLs_chr5_P2.sh
bsub < QTL_getters/get_QTLs_chr5_P3.sh
bsub < QTL_getters/get_QTLs_chr5_P4.sh
bsub < QTL_getters/get_QTLs_chr5_P5.sh
bsub < QTL_getters/get_QTLs_chr5_P6.sh
bsub < QTL_getters/get_QTLs_chr5_P7.sh
bsub < QTL_getters/get_QTLs_chr5_P8.sh
bsub < QTL_getters/get_QTLs_chr5_P9.sh
bsub < QTL_getters/get_QTLs_chr5_P10.sh
bsub < QTL_getters/get_QTLs_chr5_P11.sh
bsub < QTL_getters/get_QTLs_chr5_P12.sh
bsub < QTL_getters/get_QTLs_chr5_P13.sh
bsub < QTL_getters/get_QTLs_chr5_P14.sh
bsub < QTL_getters/get_QTLs_chr5_P15.sh

bsub < QTL_getters/get_QTLs_chr6_P0.sh
bsub < QTL_getters/get_QTLs_chr6_P1.sh
bsub < QTL_getters/get_QTLs_chr6_P2.sh
bsub < QTL_getters/get_QTLs_chr6_P3.sh
bsub < QTL_getters/get_QTLs_chr6_P4.sh
bsub < QTL_getters/get_QTLs_chr6_P5.sh
bsub < QTL_getters/get_QTLs_chr6_P6.sh
bsub < QTL_getters/get_QTLs_chr6_P7.sh
bsub < QTL_getters/get_QTLs_chr6_P8.sh
bsub < QTL_getters/get_QTLs_chr6_P9.sh
bsub < QTL_getters/get_QTLs_chr6_P10.sh
bsub < QTL_getters/get_QTLs_chr6_P11.sh
bsub < QTL_getters/get_QTLs_chr6_P12.sh
bsub < QTL_getters/get_QTLs_chr6_P13.sh
bsub < QTL_getters/get_QTLs_chr6_P14.sh
bsub < QTL_getters/get_QTLs_chr6_P15.sh

bsub < QTL_getters/get_QTLs_chr7_P0.sh
bsub < QTL_getters/get_QTLs_chr7_P1.sh
bsub < QTL_getters/get_QTLs_chr7_P2.sh
bsub < QTL_getters/get_QTLs_chr7_P3.sh
bsub < QTL_getters/get_QTLs_chr7_P4.sh
bsub < QTL_getters/get_QTLs_chr7_P5.sh
bsub < QTL_getters/get_QTLs_chr7_P6.sh
bsub < QTL_getters/get_QTLs_chr7_P7.sh
bsub < QTL_getters/get_QTLs_chr7_P8.sh
bsub < QTL_getters/get_QTLs_chr7_P9.sh
bsub < QTL_getters/get_QTLs_chr7_P10.sh
bsub < QTL_getters/get_QTLs_chr7_P11.sh
bsub < QTL_getters/get_QTLs_chr7_P12.sh
bsub < QTL_getters/get_QTLs_chr7_P13.sh
bsub < QTL_getters/get_QTLs_chr7_P14.sh
bsub < QTL_getters/get_QTLs_chr7_P15.sh

bsub < QTL_getters/get_QTLs_chr8_P0.sh
bsub < QTL_getters/get_QTLs_chr8_P1.sh
bsub < QTL_getters/get_QTLs_chr8_P2.sh
bsub < QTL_getters/get_QTLs_chr8_P3.sh
bsub < QTL_getters/get_QTLs_chr8_P4.sh
bsub < QTL_getters/get_QTLs_chr8_P5.sh
bsub < QTL_getters/get_QTLs_chr8_P6.sh
bsub < QTL_getters/get_QTLs_chr8_P7.sh
bsub < QTL_getters/get_QTLs_chr8_P8.sh
bsub < QTL_getters/get_QTLs_chr8_P9.sh
bsub < QTL_getters/get_QTLs_chr8_P10.sh
bsub < QTL_getters/get_QTLs_chr8_P11.sh
bsub < QTL_getters/get_QTLs_chr8_P12.sh
bsub < QTL_getters/get_QTLs_chr8_P13.sh
bsub < QTL_getters/get_QTLs_chr8_P14.sh
bsub < QTL_getters/get_QTLs_chr8_P15.sh

bsub < QTL_getters/get_QTLs_chr9_P0.sh
bsub < QTL_getters/get_QTLs_chr9_P1.sh
bsub < QTL_getters/get_QTLs_chr9_P2.sh
bsub < QTL_getters/get_QTLs_chr9_P3.sh
bsub < QTL_getters/get_QTLs_chr9_P4.sh
bsub < QTL_getters/get_QTLs_chr9_P5.sh
bsub < QTL_getters/get_QTLs_chr9_P6.sh
bsub < QTL_getters/get_QTLs_chr9_P7.sh
bsub < QTL_getters/get_QTLs_chr9_P8.sh
bsub < QTL_getters/get_QTLs_chr9_P9.sh
bsub < QTL_getters/get_QTLs_chr9_P10.sh
bsub < QTL_getters/get_QTLs_chr9_P11.sh
bsub < QTL_getters/get_QTLs_chr9_P12.sh
bsub < QTL_getters/get_QTLs_chr9_P13.sh
bsub < QTL_getters/get_QTLs_chr9_P14.sh
bsub < QTL_getters/get_QTLs_chr9_P15.sh

bsub < QTL_getters/get_QTLs_chr10_P0.sh
bsub < QTL_getters/get_QTLs_chr10_P1.sh
bsub < QTL_getters/get_QTLs_chr10_P2.sh
bsub < QTL_getters/get_QTLs_chr10_P3.sh
bsub < QTL_getters/get_QTLs_chr10_P4.sh
bsub < QTL_getters/get_QTLs_chr10_P5.sh
bsub < QTL_getters/get_QTLs_chr10_P6.sh
bsub < QTL_getters/get_QTLs_chr10_P7.sh
bsub < QTL_getters/get_QTLs_chr10_P8.sh
bsub < QTL_getters/get_QTLs_chr10_P9.sh
bsub < QTL_getters/get_QTLs_chr10_P10.sh
bsub < QTL_getters/get_QTLs_chr10_P11.sh
bsub < QTL_getters/get_QTLs_chr10_P12.sh
bsub < QTL_getters/get_QTLs_chr10_P13.sh
bsub < QTL_getters/get_QTLs_chr10_P14.sh
bsub < QTL_getters/get_QTLs_chr10_P15.sh

bsub < QTL_getters/get_QTLs_chr11_P0.sh
bsub < QTL_getters/get_QTLs_chr11_P1.sh
bsub < QTL_getters/get_QTLs_chr11_P2.sh
bsub < QTL_getters/get_QTLs_chr11_P3.sh
bsub < QTL_getters/get_QTLs_chr11_P4.sh
bsub < QTL_getters/get_QTLs_chr11_P5.sh
bsub < QTL_getters/get_QTLs_chr11_P6.sh
bsub < QTL_getters/get_QTLs_chr11_P7.sh
bsub < QTL_getters/get_QTLs_chr11_P8.sh
bsub < QTL_getters/get_QTLs_chr11_P9.sh
bsub < QTL_getters/get_QTLs_chr11_P10.sh
bsub < QTL_getters/get_QTLs_chr11_P11.sh
bsub < QTL_getters/get_QTLs_chr11_P12.sh
bsub < QTL_getters/get_QTLs_chr11_P13.sh
bsub < QTL_getters/get_QTLs_chr11_P14.sh
bsub < QTL_getters/get_QTLs_chr11_P15.sh

bsub < QTL_getters/get_QTLs_chr12_P0.sh
bsub < QTL_getters/get_QTLs_chr12_P1.sh
bsub < QTL_getters/get_QTLs_chr12_P2.sh
bsub < QTL_getters/get_QTLs_chr12_P3.sh
bsub < QTL_getters/get_QTLs_chr12_P4.sh
bsub < QTL_getters/get_QTLs_chr12_P5.sh
bsub < QTL_getters/get_QTLs_chr12_P6.sh
bsub < QTL_getters/get_QTLs_chr12_P7.sh
bsub < QTL_getters/get_QTLs_chr12_P8.sh
bsub < QTL_getters/get_QTLs_chr12_P9.sh
bsub < QTL_getters/get_QTLs_chr12_P10.sh
bsub < QTL_getters/get_QTLs_chr12_P11.sh
bsub < QTL_getters/get_QTLs_chr12_P12.sh
bsub < QTL_getters/get_QTLs_chr12_P13.sh
bsub < QTL_getters/get_QTLs_chr12_P14.sh
bsub < QTL_getters/get_QTLs_chr12_P15.sh

bsub < QTL_getters/get_QTLs_chr13_P0.sh
bsub < QTL_getters/get_QTLs_chr13_P1.sh
bsub < QTL_getters/get_QTLs_chr13_P2.sh
bsub < QTL_getters/get_QTLs_chr13_P3.sh
bsub < QTL_getters/get_QTLs_chr13_P4.sh
bsub < QTL_getters/get_QTLs_chr13_P5.sh
bsub < QTL_getters/get_QTLs_chr13_P6.sh
bsub < QTL_getters/get_QTLs_chr13_P7.sh
bsub < QTL_getters/get_QTLs_chr13_P8.sh
bsub < QTL_getters/get_QTLs_chr13_P9.sh
bsub < QTL_getters/get_QTLs_chr13_P10.sh
bsub < QTL_getters/get_QTLs_chr13_P11.sh
bsub < QTL_getters/get_QTLs_chr13_P12.sh
bsub < QTL_getters/get_QTLs_chr13_P13.sh
bsub < QTL_getters/get_QTLs_chr13_P14.sh
bsub < QTL_getters/get_QTLs_chr13_P15.sh

bsub < QTL_getters/get_QTLs_chr14_P0.sh
bsub < QTL_getters/get_QTLs_chr14_P1.sh
bsub < QTL_getters/get_QTLs_chr14_P2.sh
bsub < QTL_getters/get_QTLs_chr14_P3.sh
bsub < QTL_getters/get_QTLs_chr14_P4.sh
bsub < QTL_getters/get_QTLs_chr14_P5.sh
bsub < QTL_getters/get_QTLs_chr14_P6.sh
bsub < QTL_getters/get_QTLs_chr14_P7.sh
bsub < QTL_getters/get_QTLs_chr14_P8.sh
bsub < QTL_getters/get_QTLs_chr14_P9.sh
bsub < QTL_getters/get_QTLs_chr14_P10.sh
bsub < QTL_getters/get_QTLs_chr14_P11.sh
bsub < QTL_getters/get_QTLs_chr14_P12.sh
bsub < QTL_getters/get_QTLs_chr14_P13.sh
bsub < QTL_getters/get_QTLs_chr14_P14.sh
bsub < QTL_getters/get_QTLs_chr14_P15.sh

bsub < QTL_getters/get_QTLs_chr15_P0.sh
bsub < QTL_getters/get_QTLs_chr15_P1.sh
bsub < QTL_getters/get_QTLs_chr15_P2.sh
bsub < QTL_getters/get_QTLs_chr15_P3.sh
bsub < QTL_getters/get_QTLs_chr15_P4.sh
bsub < QTL_getters/get_QTLs_chr15_P5.sh
bsub < QTL_getters/get_QTLs_chr15_P6.sh
bsub < QTL_getters/get_QTLs_chr15_P7.sh
bsub < QTL_getters/get_QTLs_chr15_P8.sh
bsub < QTL_getters/get_QTLs_chr15_P9.sh
bsub < QTL_getters/get_QTLs_chr15_P10.sh
bsub < QTL_getters/get_QTLs_chr15_P11.sh
bsub < QTL_getters/get_QTLs_chr15_P12.sh
bsub < QTL_getters/get_QTLs_chr15_P13.sh
bsub < QTL_getters/get_QTLs_chr15_P14.sh
bsub < QTL_getters/get_QTLs_chr15_P15.sh

bsub < QTL_getters/get_QTLs_chr16_P0.sh
bsub < QTL_getters/get_QTLs_chr16_P1.sh
bsub < QTL_getters/get_QTLs_chr16_P2.sh
bsub < QTL_getters/get_QTLs_chr16_P3.sh
bsub < QTL_getters/get_QTLs_chr16_P4.sh
bsub < QTL_getters/get_QTLs_chr16_P5.sh
bsub < QTL_getters/get_QTLs_chr16_P6.sh
bsub < QTL_getters/get_QTLs_chr16_P7.sh
bsub < QTL_getters/get_QTLs_chr16_P8.sh
bsub < QTL_getters/get_QTLs_chr16_P9.sh
bsub < QTL_getters/get_QTLs_chr16_P10.sh
bsub < QTL_getters/get_QTLs_chr16_P11.sh
bsub < QTL_getters/get_QTLs_chr16_P12.sh
bsub < QTL_getters/get_QTLs_chr16_P13.sh
bsub < QTL_getters/get_QTLs_chr16_P14.sh
bsub < QTL_getters/get_QTLs_chr16_P15.sh

bsub < QTL_getters/get_QTLs_chr17_P0.sh
bsub < QTL_getters/get_QTLs_chr17_P1.sh
bsub < QTL_getters/get_QTLs_chr17_P2.sh
bsub < QTL_getters/get_QTLs_chr17_P3.sh
bsub < QTL_getters/get_QTLs_chr17_P4.sh
bsub < QTL_getters/get_QTLs_chr17_P5.sh
bsub < QTL_getters/get_QTLs_chr17_P6.sh
bsub < QTL_getters/get_QTLs_chr17_P7.sh
bsub < QTL_getters/get_QTLs_chr17_P8.sh
bsub < QTL_getters/get_QTLs_chr17_P9.sh
bsub < QTL_getters/get_QTLs_chr17_P10.sh
bsub < QTL_getters/get_QTLs_chr17_P11.sh
bsub < QTL_getters/get_QTLs_chr17_P12.sh
bsub < QTL_getters/get_QTLs_chr17_P13.sh
bsub < QTL_getters/get_QTLs_chr17_P14.sh
bsub < QTL_getters/get_QTLs_chr17_P15.sh

bsub < QTL_getters/get_QTLs_chr18_P0.sh
bsub < QTL_getters/get_QTLs_chr18_P1.sh
bsub < QTL_getters/get_QTLs_chr18_P2.sh
bsub < QTL_getters/get_QTLs_chr18_P3.sh
bsub < QTL_getters/get_QTLs_chr18_P4.sh
bsub < QTL_getters/get_QTLs_chr18_P5.sh
bsub < QTL_getters/get_QTLs_chr18_P6.sh
bsub < QTL_getters/get_QTLs_chr18_P7.sh
bsub < QTL_getters/get_QTLs_chr18_P8.sh
bsub < QTL_getters/get_QTLs_chr18_P9.sh
bsub < QTL_getters/get_QTLs_chr18_P10.sh
bsub < QTL_getters/get_QTLs_chr18_P11.sh
bsub < QTL_getters/get_QTLs_chr18_P12.sh
bsub < QTL_getters/get_QTLs_chr18_P13.sh
bsub < QTL_getters/get_QTLs_chr18_P14.sh
bsub < QTL_getters/get_QTLs_chr18_P15.sh

bsub < QTL_getters/get_QTLs_chr19_P0.sh
bsub < QTL_getters/get_QTLs_chr19_P1.sh
bsub < QTL_getters/get_QTLs_chr19_P2.sh
bsub < QTL_getters/get_QTLs_chr19_P3.sh
bsub < QTL_getters/get_QTLs_chr19_P4.sh
bsub < QTL_getters/get_QTLs_chr19_P5.sh
bsub < QTL_getters/get_QTLs_chr19_P6.sh
bsub < QTL_getters/get_QTLs_chr19_P7.sh
bsub < QTL_getters/get_QTLs_chr19_P8.sh
bsub < QTL_getters/get_QTLs_chr19_P9.sh
bsub < QTL_getters/get_QTLs_chr19_P10.sh
bsub < QTL_getters/get_QTLs_chr19_P11.sh
bsub < QTL_getters/get_QTLs_chr19_P12.sh
bsub < QTL_getters/get_QTLs_chr19_P13.sh
bsub < QTL_getters/get_QTLs_chr19_P14.sh
bsub < QTL_getters/get_QTLs_chr19_P15.sh

bsub < QTL_getters/get_QTLs_chr20_P0.sh
bsub < QTL_getters/get_QTLs_chr20_P1.sh
bsub < QTL_getters/get_QTLs_chr20_P2.sh
bsub < QTL_getters/get_QTLs_chr20_P3.sh
bsub < QTL_getters/get_QTLs_chr20_P4.sh
bsub < QTL_getters/get_QTLs_chr20_P5.sh
bsub < QTL_getters/get_QTLs_chr20_P6.sh
bsub < QTL_getters/get_QTLs_chr20_P7.sh
bsub < QTL_getters/get_QTLs_chr20_P8.sh
bsub < QTL_getters/get_QTLs_chr20_P9.sh
bsub < QTL_getters/get_QTLs_chr20_P10.sh
bsub < QTL_getters/get_QTLs_chr20_P11.sh
bsub < QTL_getters/get_QTLs_chr20_P12.sh
bsub < QTL_getters/get_QTLs_chr20_P13.sh
bsub < QTL_getters/get_QTLs_chr20_P14.sh
bsub < QTL_getters/get_QTLs_chr20_P15.sh

bsub < QTL_getters/get_QTLs_chr21_P0.sh
bsub < QTL_getters/get_QTLs_chr21_P1.sh
bsub < QTL_getters/get_QTLs_chr21_P2.sh
bsub < QTL_getters/get_QTLs_chr21_P3.sh
bsub < QTL_getters/get_QTLs_chr21_P4.sh
bsub < QTL_getters/get_QTLs_chr21_P5.sh
bsub < QTL_getters/get_QTLs_chr21_P6.sh
bsub < QTL_getters/get_QTLs_chr21_P7.sh
bsub < QTL_getters/get_QTLs_chr21_P8.sh
bsub < QTL_getters/get_QTLs_chr21_P9.sh
bsub < QTL_getters/get_QTLs_chr21_P10.sh
bsub < QTL_getters/get_QTLs_chr21_P11.sh
bsub < QTL_getters/get_QTLs_chr21_P12.sh
bsub < QTL_getters/get_QTLs_chr21_P13.sh
bsub < QTL_getters/get_QTLs_chr21_P14.sh
bsub < QTL_getters/get_QTLs_chr21_P15.sh

bsub < QTL_getters/get_QTLs_chr22_P0.sh
bsub < QTL_getters/get_QTLs_chr22_P1.sh
bsub < QTL_getters/get_QTLs_chr22_P2.sh
bsub < QTL_getters/get_QTLs_chr22_P3.sh
bsub < QTL_getters/get_QTLs_chr22_P4.sh
bsub < QTL_getters/get_QTLs_chr22_P5.sh
bsub < QTL_getters/get_QTLs_chr22_P6.sh
bsub < QTL_getters/get_QTLs_chr22_P7.sh
bsub < QTL_getters/get_QTLs_chr22_P8.sh
bsub < QTL_getters/get_QTLs_chr22_P9.sh
bsub < QTL_getters/get_QTLs_chr22_P10.sh
bsub < QTL_getters/get_QTLs_chr22_P11.sh
bsub < QTL_getters/get_QTLs_chr22_P12.sh
bsub < QTL_getters/get_QTLs_chr22_P13.sh
bsub < QTL_getters/get_QTLs_chr22_P14.sh
bsub < QTL_getters/get_QTLs_chr22_P15.sh

bsub < QTL_getters/get_QTLs_chrMT_P0.sh
bsub < QTL_getters/get_QTLs_chrMT_P1.sh
bsub < QTL_getters/get_QTLs_chrMT_P2.sh
bsub < QTL_getters/get_QTLs_chrMT_P3.sh
bsub < QTL_getters/get_QTLs_chrMT_P4.sh
bsub < QTL_getters/get_QTLs_chrMT_P5.sh
bsub < QTL_getters/get_QTLs_chrMT_P6.sh
bsub < QTL_getters/get_QTLs_chrMT_P7.sh
bsub < QTL_getters/get_QTLs_chrMT_P8.sh
bsub < QTL_getters/get_QTLs_chrMT_P9.sh
bsub < QTL_getters/get_QTLs_chrMT_P10.sh
bsub < QTL_getters/get_QTLs_chrMT_P11.sh
bsub < QTL_getters/get_QTLs_chrMT_P12.sh
bsub < QTL_getters/get_QTLs_chrMT_P13.sh
bsub < QTL_getters/get_QTLs_chrMT_P14.sh
bsub < QTL_getters/get_QTLs_chrMT_P15.sh

bsub < QTL_getters/get_QTLs_chrX_P0.sh
bsub < QTL_getters/get_QTLs_chrX_P1.sh
bsub < QTL_getters/get_QTLs_chrX_P2.sh
bsub < QTL_getters/get_QTLs_chrX_P3.sh
bsub < QTL_getters/get_QTLs_chrX_P4.sh
bsub < QTL_getters/get_QTLs_chrX_P5.sh
bsub < QTL_getters/get_QTLs_chrX_P6.sh
bsub < QTL_getters/get_QTLs_chrX_P7.sh
bsub < QTL_getters/get_QTLs_chrX_P8.sh
bsub < QTL_getters/get_QTLs_chrX_P9.sh
bsub < QTL_getters/get_QTLs_chrX_P10.sh
bsub < QTL_getters/get_QTLs_chrX_P11.sh
bsub < QTL_getters/get_QTLs_chrX_P12.sh
bsub < QTL_getters/get_QTLs_chrX_P13.sh
bsub < QTL_getters/get_QTLs_chrX_P14.sh
bsub < QTL_getters/get_QTLs_chrX_P15.sh

bsub < QTL_getters/get_QTLs_chrXY_P0.sh
bsub < QTL_getters/get_QTLs_chrXY_P1.sh
bsub < QTL_getters/get_QTLs_chrXY_P2.sh
bsub < QTL_getters/get_QTLs_chrXY_P3.sh
bsub < QTL_getters/get_QTLs_chrXY_P4.sh
bsub < QTL_getters/get_QTLs_chrXY_P5.sh
bsub < QTL_getters/get_QTLs_chrXY_P6.sh
bsub < QTL_getters/get_QTLs_chrXY_P7.sh
bsub < QTL_getters/get_QTLs_chrXY_P8.sh
bsub < QTL_getters/get_QTLs_chrXY_P9.sh
bsub < QTL_getters/get_QTLs_chrXY_P10.sh
bsub < QTL_getters/get_QTLs_chrXY_P11.sh
bsub < QTL_getters/get_QTLs_chrXY_P12.sh
bsub < QTL_getters/get_QTLs_chrXY_P13.sh
bsub < QTL_getters/get_QTLs_chrXY_P14.sh
bsub < QTL_getters/get_QTLs_chrXY_P15.sh

bsub < QTL_getters/get_QTLs_chrY_P0.sh
bsub < QTL_getters/get_QTLs_chrY_P1.sh
bsub < QTL_getters/get_QTLs_chrY_P2.sh
bsub < QTL_getters/get_QTLs_chrY_P3.sh
bsub < QTL_getters/get_QTLs_chrY_P4.sh
bsub < QTL_getters/get_QTLs_chrY_P5.sh
bsub < QTL_getters/get_QTLs_chrY_P6.sh
bsub < QTL_getters/get_QTLs_chrY_P7.sh
bsub < QTL_getters/get_QTLs_chrY_P8.sh
bsub < QTL_getters/get_QTLs_chrY_P9.sh
bsub < QTL_getters/get_QTLs_chrY_P10.sh
bsub < QTL_getters/get_QTLs_chrY_P11.sh
bsub < QTL_getters/get_QTLs_chrY_P12.sh
bsub < QTL_getters/get_QTLs_chrY_P13.sh
bsub < QTL_getters/get_QTLs_chrY_P14.sh
bsub < QTL_getters/get_QTLs_chrY_P15.sh


bsub < QTL_getters/get_QTLs_chr1_P16.sh
bsub < QTL_getters/get_QTLs_chr2_P16.sh
bsub < QTL_getters/get_QTLs_chr3_P16.sh
bsub < QTL_getters/get_QTLs_chr4_P16.sh
bsub < QTL_getters/get_QTLs_chr5_P16.sh
bsub < QTL_getters/get_QTLs_chr6_P16.sh
bsub < QTL_getters/get_QTLs_chr7_P16.sh
bsub < QTL_getters/get_QTLs_chr8_P16.sh
bsub < QTL_getters/get_QTLs_chr9_P16.sh
bsub < QTL_getters/get_QTLs_chr10_P16.sh
bsub < QTL_getters/get_QTLs_chr11_P16.sh
bsub < QTL_getters/get_QTLs_chr12_P16.sh
bsub < QTL_getters/get_QTLs_chr13_P16.sh
bsub < QTL_getters/get_QTLs_chr14_P16.sh
bsub < QTL_getters/get_QTLs_chr15_P16.sh
bsub < QTL_getters/get_QTLs_chr16_P16.sh
bsub < QTL_getters/get_QTLs_chr17_P16.sh
bsub < QTL_getters/get_QTLs_chr18_P16.sh
bsub < QTL_getters/get_QTLs_chr19_P16.sh
bsub < QTL_getters/get_QTLs_chr20_P16.sh
bsub < QTL_getters/get_QTLs_chr21_P16.sh
bsub < QTL_getters/get_QTLs_chr22_P16.sh
bsub < QTL_getters/get_QTLs_chrMT_P16.sh
bsub < QTL_getters/get_QTLs_chrX_P16.sh
bsub < QTL_getters/get_QTLs_chrXY_P16.sh
bsub < QTL_getters/get_QTLs_chrY_P16.sh
